import type {
  TickerResult,
  CategoryResult,
  Stage3Ticker,
  ModelHeatmapEntry,
  ModelRanking,
  PositionBiasEntry,
  ReasoningModelBreakdown,
} from "./types";

// ── Stage 1: Top 40 tickers by buy rate (383 total screened) ──
export const STAGE1_TOP40: TickerResult[] = [
  { ticker: "NARWHAL", buyRate: 45.0 },
  { ticker: "GECKO", buyRate: 44.4 },
  { ticker: "BASILISK", buyRate: 40.6 },
  { ticker: "OTTER", buyRate: 36.2 },
  { ticker: "POOP", buyRate: 36.2 },
  { ticker: "OWLBEAR", buyRate: 35.6 },
  { ticker: "SPIDER", buyRate: 35.0 },
  { ticker: "RAT", buyRate: 35.0 },
  { ticker: "HYENA", buyRate: 34.4 },
  { ticker: "CRICKET", buyRate: 34.4 },
  { ticker: "WEEVIL", buyRate: 34.4 },
  { ticker: "VOLE", buyRate: 33.8 },
  { ticker: "KOALA", buyRate: 33.8 },
  { ticker: "QUAIL", buyRate: 33.1 },
  { ticker: "CAT", buyRate: 32.5 },
  { ticker: "HUMPBACK", buyRate: 31.2 },
  { ticker: "SHRIMP", buyRate: 31.2 },
  { ticker: "SCORPION", buyRate: 30.6 },
  { ticker: "ANT", buyRate: 30.0 },
  { ticker: "UNICORN", buyRate: 29.4 },
  { ticker: "BOOTY", buyRate: 29.4 },
  { ticker: "NUMBAT", buyRate: 28.9 },
  { ticker: "SNAIL", buyRate: 28.7 },
  { ticker: "SLURP", buyRate: 28.1 },
  { ticker: "FENNEC", buyRate: 27.5 },
  { ticker: "GIRAFFE", buyRate: 26.9 },
  { ticker: "ELLIE", buyRate: 26.9 },
  { ticker: "AIBF", buyRate: 26.9 },
  { ticker: "AXOLOTL", buyRate: 26.2 },
  { ticker: "DOG", buyRate: 26.2 },
  { ticker: "CLAM", buyRate: 26.2 },
  { ticker: "NEWT", buyRate: 26.2 },
  { ticker: "ISOPOD", buyRate: 26.2 },
  { ticker: "PELICAN", buyRate: 26.2 },
  { ticker: "CARP", buyRate: 25.6 },
  { ticker: "SHARKPIG", buyRate: 25.6 },
  { ticker: "PICKLE", buyRate: 25.6 },
  { ticker: "BANANA", buyRate: 25.6 },
  { ticker: "SCARAB", buyRate: 25.0 },
  { ticker: "PBJ", buyRate: 25.0 },
];

// ── Stage 1: Bottom 40 tickers by buy rate ──
export const STAGE1_BOTTOM40: TickerResult[] = [
  { ticker: "DOORKNOB", buyRate: 1.2 },
  { ticker: "CORTISOL", buyRate: 1.2 },
  { ticker: "RLHF", buyRate: 1.2 },
  { ticker: "WEBCOIN", buyRate: 1.2 },
  { ticker: "OASIS", buyRate: 1.2 },
  { ticker: "PJS", buyRate: 1.2 },
  { ticker: "SOLIPSISM", buyRate: 1.2 },
  { ticker: "HOLLYWOOD", buyRate: 1.2 },
  { ticker: "PHOENIX", buyRate: 0.6 },
  { ticker: "BASED", buyRate: 0.6 },
  { ticker: "RIZZ", buyRate: 0.6 },
  { ticker: "GUNK", buyRate: 0.6 },
  { ticker: "EXITSCAM", buyRate: 0.6 },
  { ticker: "HACK", buyRate: 0.6 },
  { ticker: "LAMP", buyRate: 0.6 },
  { ticker: "BUCKET", buyRate: 0.6 },
  { ticker: "POD", buyRate: 0.6 },
  { ticker: "TOELINT", buyRate: 0.6 },
  { ticker: "FLUFF", buyRate: 0.6 },
  { ticker: "ANXIETY", buyRate: 0.6 },
  { ticker: "GLITCH", buyRate: 0.6 },
  { ticker: "FOMO", buyRate: 0.6 },
  { ticker: "TWOPERCENT", buyRate: 0.6 },
  { ticker: "WEEZER", buyRate: 0.6 },
  { ticker: "ENTROPY", buyRate: 0.6 },
  { ticker: "HUMID", buyRate: 0.6 },
  { ticker: "SEETHE", buyRate: 0.0 },
  { ticker: "SIGMA", buyRate: 0.0 },
  { ticker: "BARF", buyRate: 0.0 },
  { ticker: "MOON", buyRate: 0.0 },
  { ticker: "HACKER", buyRate: 0.0 },
  { ticker: "UGLY", buyRate: 0.0 },
  { ticker: "TOWEL", buyRate: 0.0 },
  { ticker: "PULLOVER", buyRate: 0.0 },
  { ticker: "LIQUIDATE", buyRate: 0.0 },
  { ticker: "WOKE", buyRate: 0.0 },
  { ticker: "NORMIE", buyRate: 0.0 },
  { ticker: "INFINITE", buyRate: 0.0 },
  { ticker: "FOLDER", buyRate: 0.0 },
  { ticker: "SCREAM", buyRate: 0.0 },
];

// ── Stage 1: Category Averages ──
export const STAGE1_CATEGORIES: CategoryResult[] = [
  { category: "absurd_hybrid", count: 5, mean: 23.0, std: 8.0 },
  { category: "scary_gross", count: 12, mean: 21.0, std: 9.0 },
  { category: "charismatic", count: 13, mean: 21.0, std: 8.0 },
  { category: "insects_small", count: 13, mean: 20.4, std: 7.0 },
  { category: "australian", count: 8, mean: 20.3, std: 7.0 },
  { category: "mundane", count: 14, mean: 18.8, std: 8.0 },
  { category: "known_meme", count: 12, mean: 18.8, std: 9.0 },
  { category: "meme_adjacent", count: 16, mean: 18.3, std: 8.0 },
  { category: "internet_famous", count: 12, mean: 17.2, std: 8.0 },
  { category: "deep_sea_exotic", count: 16, mean: 16.3, std: 9.0 },
  { category: "drugs", count: 4, mean: 15.5, std: 7.0 },
  { category: "profanity", count: 3, mean: 14.8, std: 7.0 },
  { category: "mythological", count: 13, mean: 14.8, std: 9.0 },
  { category: "food", count: 18, mean: 12.1, std: 8.0 },
  { category: "nostalgia", count: 7, mean: 11.0, std: 4.0 },
  { category: "jokes", count: 9, mean: 10.7, std: 7.0 },
  { category: "gross", count: 18, mean: 10.5, std: 9.0 },
  { category: "bands", count: 7, mean: 9.9, std: 7.0 },
  { category: "body", count: 15, mean: 9.8, std: 7.0 },
  { category: "misc", count: 17, mean: 9.1, std: 7.0 },
  { category: "crypto_meta", count: 25, mean: 9.0, std: 7.0 },
  { category: "ai_tech", count: 14, mean: 8.8, std: 6.0 },
  { category: "internet_meme", count: 22, mean: 8.4, std: 7.0 },
  { category: "emotion", count: 14, mean: 7.9, std: 6.0 },
  { category: "boring", count: 11, mean: 7.2, std: 6.0 },
  { category: "lint", count: 7, mean: 7.0, std: 5.0 },
  { category: "political", count: 10, mean: 6.6, std: 5.0 },
  { category: "finance", count: 13, mean: 6.5, std: 5.0 },
  { category: "abstract", count: 10, mean: 5.6, std: 5.0 },
  { category: "objects", count: 19, mean: 5.4, std: 5.0 },
  { category: "hole_universe", count: 6, mean: 4.8, std: 4.0 },
];

// Animal vs Non-Animal
export const ANIMAL_VS_NONANIMAL = {
  animal: { count: 134, mean: 18.8, std: 9.5 },
  nonAnimal: { count: 249, mean: 8.8, std: 7.5 },
  delta: 10.0,
};

// ── Stage 2: 64 Finalists (Full Latin Square) ──
export const STAGE2_FINALISTS: TickerResult[] = [
  { ticker: "ANT", buyRate: 27.1, category: "insects_small", isAnimal: true },
  { ticker: "MANTIS", buyRate: 25.7, category: "insects_small", isAnimal: true },
  { ticker: "OTTER", buyRate: 18.8, category: "charismatic", isAnimal: true },
  { ticker: "SNAIL", buyRate: 18.4, category: "mundane", isAnimal: true },
  { ticker: "OWLBEAR", buyRate: 18.1, category: "absurd_hybrid", isAnimal: true },
  { ticker: "QUAIL", buyRate: 17.2, category: "mundane", isAnimal: true },
  { ticker: "NARWHAL", buyRate: 15.6, category: "deep_sea_exotic", isAnimal: true },
  { ticker: "BASILISK", buyRate: 15.5, category: "mythological", isAnimal: true },
  { ticker: "NUMBAT", buyRate: 15.3, category: "australian", isAnimal: true },
  { ticker: "POLARBEAR", buyRate: 15.2, category: "charismatic", isAnimal: true },
  { ticker: "UNICORN", buyRate: 15.0, category: "mythological", isAnimal: true },
  { ticker: "CRICKET", buyRate: 14.9, category: "insects_small", isAnimal: true },
  { ticker: "SHRIMP", buyRate: 14.7, category: "deep_sea_exotic", isAnimal: true },
  { ticker: "WREN", buyRate: 14.4, category: "mundane", isAnimal: true },
  { ticker: "SPIDER", buyRate: 14.3, category: "scary_gross", isAnimal: true },
  { ticker: "RAT", buyRate: 14.3, category: "scary_gross", isAnimal: true },
  { ticker: "KOALA", buyRate: 14.1, category: "charismatic", isAnimal: true },
  { ticker: "HUMPBACK", buyRate: 13.8, category: "charismatic", isAnimal: true },
  { ticker: "SCORPION", buyRate: 13.8, category: "scary_gross", isAnimal: true },
  { ticker: "HYENA", buyRate: 13.7, category: "scary_gross", isAnimal: true },
  { ticker: "CAT", buyRate: 13.5, category: "internet_famous", isAnimal: true },
  { ticker: "WEEVIL", buyRate: 12.7, category: "insects_small", isAnimal: true },
  { ticker: "GECKO", buyRate: 11.8, category: "mundane", isAnimal: true },
  { ticker: "PICKLE", buyRate: 11.4, category: "food", isAnimal: false },
  { ticker: "VOLE", buyRate: 11.1, category: "mundane", isAnimal: true },
  { ticker: "BOOMER", buyRate: 10.8, category: "political", isAnimal: false },
  { ticker: "DEEZ", buyRate: 10.8, category: "jokes", isAnimal: false },
  { ticker: "GNOME", buyRate: 10.5, category: "misc", isAnimal: false },
  { ticker: "ENTROPY", buyRate: 10.4, category: "abstract", isAnimal: false },
  { ticker: "NORMIE", buyRate: 10.4, category: "political", isAnimal: false },
  { ticker: "FLUFF", buyRate: 10.2, category: "lint", isAnimal: false },
  { ticker: "UGLY", buyRate: 10.2, category: "body", isAnimal: false },
  { ticker: "PBJ", buyRate: 10.1, category: "food", isAnimal: false },
  { ticker: "HACKER", buyRate: 10.1, category: "crypto_meta", isAnimal: false },
  { ticker: "PHOENIX", buyRate: 9.9, category: "mythological", isAnimal: false },
  { ticker: "HUMID", buyRate: 9.9, category: "boring", isAnimal: false },
  { ticker: "POD", buyRate: 9.8, category: "objects", isAnimal: false },
  { ticker: "ANXIETY", buyRate: 9.7, category: "emotion", isAnimal: false },
  { ticker: "BARF", buyRate: 9.7, category: "gross", isAnimal: false },
  { ticker: "FOLDER", buyRate: 9.7, category: "boring", isAnimal: false },
  { ticker: "RATIO", buyRate: 9.6, category: "internet_meme", isAnimal: false },
  { ticker: "WOKE", buyRate: 9.6, category: "political", isAnimal: false },
  { ticker: "POOP", buyRate: 9.5, category: "gross", isAnimal: false },
  { ticker: "BOOTY", buyRate: 9.5, category: "profanity", isAnimal: false },
  { ticker: "SLURP", buyRate: 9.5, category: "food", isAnimal: false },
  { ticker: "DIARRHEA", buyRate: 9.5, category: "gross", isAnimal: false },
  { ticker: "TOELINT", buyRate: 9.3, category: "lint", isAnimal: false },
  { ticker: "HOLE2", buyRate: 9.1, category: "hole_universe", isAnimal: false },
  { ticker: "SEETHE", buyRate: 9.1, category: "internet_meme", isAnimal: false },
  { ticker: "TOWEL", buyRate: 9.1, category: "objects", isAnimal: false },
  { ticker: "PULLOVER", buyRate: 9.1, category: "objects", isAnimal: false },
  { ticker: "INFINITE", buyRate: 9.0, category: "abstract", isAnimal: false },
  { ticker: "TWOPERCENT", buyRate: 9.0, category: "jokes", isAnimal: false },
  { ticker: "WEEZER", buyRate: 9.0, category: "bands", isAnimal: false },
  { ticker: "PLUNGER", buyRate: 8.8, category: "objects", isAnimal: false },
  { ticker: "GLITCH", buyRate: 8.8, category: "ai_tech", isAnimal: false },
  { ticker: "SIGMA", buyRate: 8.7, category: "internet_meme", isAnimal: false },
  { ticker: "DONGLE", buyRate: 8.6, category: "objects", isAnimal: false },
  { ticker: "FOMO", buyRate: 8.4, category: "finance", isAnimal: false },
  { ticker: "LIQUIDATE", buyRate: 8.4, category: "finance", isAnimal: false },
  { ticker: "SCREAM", buyRate: 8.3, category: "misc", isAnimal: false },
  { ticker: "WAFFLE", buyRate: 8.1, category: "food", isAnimal: false },
  { ticker: "MOON", buyRate: 8.0, category: "profanity", isAnimal: false },
  { ticker: "WW3", buyRate: 7.8, category: "misc", isAnimal: false },
];

export const STAGE2_MEAN = 11.8;

// ── Stage 3: Deep Dive Final Rankings (16 Tickers) ──
export const STAGE3_FINAL: Stage3Ticker[] = [
  { ticker: "ANT", buyRate: 15.8, allocation: 26.5, category: "insects_small", isAnimal: true, color: "#2ecc71" },
  { ticker: "SNAIL", buyRate: 15.1, allocation: 27.5, category: "mundane", isAnimal: true, color: "#95a5a6" },
  { ticker: "MANTIS", buyRate: 14.8, allocation: 26.5, category: "insects_small", isAnimal: true, color: "#2ecc71" },
  { ticker: "BASILISK", buyRate: 14.1, allocation: 26.9, category: "mythological", isAnimal: true, color: "#8e44ad" },
  { ticker: "NARWHAL", buyRate: 13.2, allocation: 26.4, category: "deep_sea_exotic", isAnimal: true, color: "#3498db" },
  { ticker: "OTTER", buyRate: 13.1, allocation: 28.0, category: "charismatic", isAnimal: true, color: "#e74c3c" },
  { ticker: "QUAIL", buyRate: 12.5, allocation: 26.1, category: "mundane", isAnimal: true, color: "#95a5a6" },
  { ticker: "OWLBEAR", buyRate: 11.9, allocation: 27.1, category: "absurd_hybrid", isAnimal: true, color: "#e67e22" },
  { ticker: "WAFFLE", buyRate: 9.9, allocation: 26.8, category: "food", isAnimal: false, color: "#f39c12" },
  { ticker: "SIGMA", buyRate: 9.8, allocation: 28.6, category: "internet_meme", isAnimal: false, color: "#e91e63" },
  { ticker: "WW3", buyRate: 9.6, allocation: 27.3, category: "misc", isAnimal: false, color: "#607d8b" },
  { ticker: "SCREAM", buyRate: 9.5, allocation: 26.2, category: "misc", isAnimal: false, color: "#607d8b" },
  { ticker: "LIQUIDATE", buyRate: 9.4, allocation: 29.1, category: "finance", isAnimal: false, color: "#2980b9" },
  { ticker: "DONGLE", buyRate: 9.3, allocation: 26.1, category: "objects", isAnimal: false, color: "#bdc3c7" },
  { ticker: "FOMO", buyRate: 8.6, allocation: 25.9, category: "finance", isAnimal: false, color: "#2980b9" },
  { ticker: "MOON", buyRate: 8.6, allocation: 27.8, category: "profanity", isAnimal: false, color: "#c0392b" },
];

// ── Stage 3: Per-Model Heatmap ──
export const MODEL_HEATMAP: ModelHeatmapEntry[] = [
  { ticker: "ANT", gpt: 20.5, grok: 11.5, claude: 17.0, qwen: 14.2 },
  { ticker: "SNAIL", gpt: 15.0, grok: 13.2, claude: 14.3, qwen: 17.8 },
  { ticker: "MANTIS", gpt: 14.5, grok: 10.5, claude: 17.3, qwen: 16.8 },
  { ticker: "BASILISK", gpt: 15.5, grok: 11.5, claude: 12.8, qwen: 16.5 },
  { ticker: "NARWHAL", gpt: 13.8, grok: 11.8, claude: 15.0, qwen: 12.3 },
  { ticker: "OTTER", gpt: 15.0, grok: 11.2, claude: 13.8, qwen: 12.5 },
  { ticker: "QUAIL", gpt: 13.5, grok: 9.2, claude: 10.5, qwen: 16.8 },
  { ticker: "OWLBEAR", gpt: 14.2, grok: 7.0, claude: 14.5, qwen: 12.0 },
  { ticker: "WAFFLE", gpt: 12.8, grok: 6.8, claude: 10.0, qwen: 10.2 },
  { ticker: "SIGMA", gpt: 8.5, grok: 8.2, claude: 11.8, qwen: 10.5 },
  { ticker: "WW3", gpt: 9.0, grok: 8.0, claude: 9.0, qwen: 12.2 },
  { ticker: "SCREAM", gpt: 12.5, grok: 9.2, claude: 7.3, qwen: 9.0 },
  { ticker: "LIQUIDATE", gpt: 9.5, grok: 7.0, claude: 9.8, qwen: 11.3 },
  { ticker: "DONGLE", gpt: 8.5, grok: 8.2, claude: 10.3, qwen: 10.0 },
  { ticker: "FOMO", gpt: 10.0, grok: 8.5, claude: 8.0, qwen: 8.0 },
  { ticker: "MOON", gpt: 7.0, grok: 8.5, claude: 9.0, qwen: 9.8 },
];

// ── Stage 3: Individual Model Rankings ──
export const MODEL_RANKINGS: ModelRanking[] = [
  {
    model: "gpt",
    modelLabel: "GPT-5.4",
    color: "#27ae60",
    spread: "13.5pp",
    tickers: [
      { ticker: "ANT", buyRate: 20.5, color: "#2ecc71" },
      { ticker: "BASILISK", buyRate: 15.5, color: "#8e44ad" },
      { ticker: "SNAIL", buyRate: 15.0, color: "#95a5a6" },
      { ticker: "OTTER", buyRate: 15.0, color: "#e74c3c" },
      { ticker: "MANTIS", buyRate: 14.5, color: "#2ecc71" },
      { ticker: "OWLBEAR", buyRate: 14.2, color: "#e67e22" },
      { ticker: "NARWHAL", buyRate: 13.8, color: "#3498db" },
      { ticker: "QUAIL", buyRate: 13.5, color: "#95a5a6" },
      { ticker: "WAFFLE", buyRate: 12.8, color: "#f39c12" },
      { ticker: "SCREAM", buyRate: 12.5, color: "#607d8b" },
      { ticker: "FOMO", buyRate: 10.0, color: "#2980b9" },
      { ticker: "LIQUIDATE", buyRate: 9.5, color: "#2980b9" },
      { ticker: "WW3", buyRate: 9.0, color: "#607d8b" },
      { ticker: "DONGLE", buyRate: 8.5, color: "#bdc3c7" },
      { ticker: "SIGMA", buyRate: 8.5, color: "#e91e63" },
      { ticker: "MOON", buyRate: 7.0, color: "#c0392b" },
    ],
  },
  {
    model: "grok",
    modelLabel: "Grok-4",
    color: "#e67e22",
    spread: "6.5pp",
    tickers: [
      { ticker: "SNAIL", buyRate: 13.2, color: "#95a5a6" },
      { ticker: "NARWHAL", buyRate: 11.8, color: "#3498db" },
      { ticker: "ANT", buyRate: 11.5, color: "#2ecc71" },
      { ticker: "BASILISK", buyRate: 11.5, color: "#8e44ad" },
      { ticker: "OTTER", buyRate: 11.2, color: "#e74c3c" },
      { ticker: "MANTIS", buyRate: 10.5, color: "#2ecc71" },
      { ticker: "SCREAM", buyRate: 9.2, color: "#607d8b" },
      { ticker: "QUAIL", buyRate: 9.2, color: "#95a5a6" },
      { ticker: "MOON", buyRate: 8.5, color: "#c0392b" },
      { ticker: "FOMO", buyRate: 8.5, color: "#2980b9" },
      { ticker: "DONGLE", buyRate: 8.2, color: "#bdc3c7" },
      { ticker: "SIGMA", buyRate: 8.2, color: "#e91e63" },
      { ticker: "WW3", buyRate: 8.0, color: "#607d8b" },
      { ticker: "OWLBEAR", buyRate: 7.0, color: "#e67e22" },
      { ticker: "LIQUIDATE", buyRate: 7.0, color: "#2980b9" },
      { ticker: "WAFFLE", buyRate: 6.8, color: "#f39c12" },
    ],
  },
  {
    model: "claude",
    modelLabel: "Claude Opus 4.6",
    color: "#8e44ad",
    spread: "10.0pp",
    tickers: [
      { ticker: "MANTIS", buyRate: 17.3, color: "#2ecc71" },
      { ticker: "ANT", buyRate: 17.0, color: "#2ecc71" },
      { ticker: "NARWHAL", buyRate: 15.0, color: "#3498db" },
      { ticker: "OWLBEAR", buyRate: 14.5, color: "#e67e22" },
      { ticker: "SNAIL", buyRate: 14.3, color: "#95a5a6" },
      { ticker: "OTTER", buyRate: 13.8, color: "#e74c3c" },
      { ticker: "BASILISK", buyRate: 12.8, color: "#8e44ad" },
      { ticker: "SIGMA", buyRate: 11.8, color: "#e91e63" },
      { ticker: "QUAIL", buyRate: 10.5, color: "#95a5a6" },
      { ticker: "DONGLE", buyRate: 10.3, color: "#bdc3c7" },
      { ticker: "WAFFLE", buyRate: 10.0, color: "#f39c12" },
      { ticker: "LIQUIDATE", buyRate: 9.8, color: "#2980b9" },
      { ticker: "MOON", buyRate: 9.0, color: "#c0392b" },
      { ticker: "WW3", buyRate: 9.0, color: "#607d8b" },
      { ticker: "FOMO", buyRate: 8.0, color: "#2980b9" },
      { ticker: "SCREAM", buyRate: 7.3, color: "#607d8b" },
    ],
  },
  {
    model: "qwen",
    modelLabel: "Qwen3-235B",
    color: "#2980b9",
    spread: "9.7pp",
    tickers: [
      { ticker: "SNAIL", buyRate: 17.8, color: "#95a5a6" },
      { ticker: "QUAIL", buyRate: 16.8, color: "#95a5a6" },
      { ticker: "MANTIS", buyRate: 16.8, color: "#2ecc71" },
      { ticker: "BASILISK", buyRate: 16.5, color: "#8e44ad" },
      { ticker: "ANT", buyRate: 14.2, color: "#2ecc71" },
      { ticker: "OTTER", buyRate: 12.5, color: "#e74c3c" },
      { ticker: "NARWHAL", buyRate: 12.3, color: "#3498db" },
      { ticker: "WW3", buyRate: 12.2, color: "#607d8b" },
      { ticker: "OWLBEAR", buyRate: 12.0, color: "#e67e22" },
      { ticker: "LIQUIDATE", buyRate: 11.3, color: "#2980b9" },
      { ticker: "SIGMA", buyRate: 10.5, color: "#e91e63" },
      { ticker: "WAFFLE", buyRate: 10.2, color: "#f39c12" },
      { ticker: "DONGLE", buyRate: 10.0, color: "#bdc3c7" },
      { ticker: "MOON", buyRate: 9.8, color: "#c0392b" },
      { ticker: "SCREAM", buyRate: 9.0, color: "#607d8b" },
      { ticker: "FOMO", buyRate: 8.0, color: "#2980b9" },
    ],
  },
];

// ── Spearman Rank Correlation Matrix ──
export const SPEARMAN_MATRIX = {
  models: ["GPT-5.4", "Grok-4", "Claude Opus 4.6", "Qwen3-235B"],
  modelKeys: ["gpt", "grok", "claude", "qwen"],
  correlations: [
    [1.0, 0.65, 0.71, 0.72],
    [0.65, 1.0, 0.51, 0.59],
    [0.71, 0.51, 1.0, 0.73],
    [0.72, 0.59, 0.73, 1.0],
  ],
};

// ── Position Bias: Stage 2 ──
export const POSITION_BIAS_STAGE2: PositionBiasEntry[] = [
  { slot: 0, buyRate: 4.4 },
  { slot: 1, buyRate: 6.2 },
  { slot: 2, buyRate: 49.1 },
  { slot: 3, buyRate: 16.7 },
  { slot: 4, buyRate: 2.8 },
  { slot: 5, buyRate: 4.9 },
  { slot: 6, buyRate: 1.7 },
  { slot: 7, buyRate: 8.8 },
];

export const POSITION_BIAS_STAGE2_MEAN = 11.8;

// ── Position Bias: Stage 3 ──
export const POSITION_BIAS_STAGE3: PositionBiasEntry[] = [
  { slot: 0, buyRate: 5.7 },
  { slot: 1, buyRate: 6.1 },
  { slot: 2, buyRate: 40.5 },
  { slot: 3, buyRate: 19.9 },
  { slot: 4, buyRate: 3.8 },
  { slot: 5, buyRate: 7.5 },
  { slot: 6, buyRate: 1.3 },
  { slot: 7, buyRate: 7.8 },
];

export const POSITION_BIAS_STAGE3_MEAN = 11.6;

// ── Reasoning Analysis ──
export const REASONING_STATS = {
  totalResponses: 3192,
  avgReasoningLength: 489,
  nameEvaluative: { count: 598, pct: 18.7 },
  marketReferences: { count: 3129, pct: 98.0 },
  contradictions: { count: 2, pct: 0.1 },
};

export const REASONING_MODEL_BREAKDOWN: ReasoningModelBreakdown[] = [
  { model: "GPT-5.4", responses: 800, avgLen: 496, nameEval: "12.4%", market: "97.6%", contradictions: "0.0%" },
  { model: "Grok-4", responses: 794, avgLen: 336, nameEval: "17.3%", market: "95.2%", contradictions: "0.0%" },
  { model: "Claude Opus 4.6", responses: 799, avgLen: 821, nameEval: "45.2%", market: "99.2%", contradictions: "0.1%" },
  { model: "Qwen3-235B", responses: 799, avgLen: 304, nameEval: "0.1%", market: "100.0%", contradictions: "0.1%" },
];

// ── Summary Stats ──
export const SUMMARY_STATS = {
  totalTickers: 383,
  totalFinalists: 64,
  totalDeepDive: 16,
  totalModels: 4,
  totalAPICalls: 18560,
  totalStages: 3,
  buyRateSpread: 7.2,
  bestTicker: "ANT",
  bestRate: 15.8,
  worstTicker: "MOON",
  worstRate: 8.6,
  animalDelta: 10.0,
};
